name: Build Kumo
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from build.gradle.kts
        id: get_version
        run: |
          VERSION=$(grep 'versionName =' app/build.gradle.kts | cut -d '"' -f 2)
          echo "Found version: $VERSION"
          
          LAST_TAG=$(git tag -l "v${VERSION}*" --sort=-v:refname | head -n 1)
          
          if [[ -z "$LAST_TAG" ]]; then
            NEW_TAG="v${VERSION}.0"
          else
            LAST_INCREMENT=$(echo "$LAST_TAG" | awk -F'.' '{print $NF}')
            if [[ "$LAST_INCREMENT" =~ ^[0-9]+$ ]]; then
              NEXT_INCREMENT=$((LAST_INCREMENT + 1))
              NEW_TAG="v${VERSION}.${NEXT_INCREMENT}"
            else
              NEW_TAG="v${VERSION}.1"
            fi
          fi
          
          echo "New tag: $NEW_TAG"
          echo "TAG=${NEW_TAG}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: gradle

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG=$(git log -n 20 --pretty=format:"- %h %s")
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Decode keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d > app/nube.p12

      - name: Build release APK
        run: |
          ./gradlew assembleRelease --stacktrace --parallel --max-workers=$(nproc)

      - name: Sign APK
        run: |
          ANDROID_BUILD_TOOLS="$ANDROID_HOME/build-tools/$(ls $ANDROID_HOME/build-tools | sort -V | tail -n1)"
          UNSIGNED_APK="app/build/outputs/apk/release/app-release-unsigned.apk"
          SIGNED_APK="app/build/outputs/apk/release/kumo-${{ steps.get_version.outputs.VERSION }}-release-signed.apk"

          if [ ! -f "$UNSIGNED_APK" ]; then
            echo "Unsigned universal APK not found!"
            exit 1
          fi

          "$ANDROID_BUILD_TOOLS/apksigner" sign \
            --ks app/nube.p12 \
            --ks-key-alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.RELEASE_KEY_PASSWORD }}" \
            --out "$SIGNED_APK" \
            "$UNSIGNED_APK"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.TAG }}
          name: "Kumo ${{ steps.get_version.outputs.TAG }}"
          files: |
            app/build/outputs/apk/release/kumo-${{ steps.get_version.outputs.VERSION }}-release-signed.apk
          body: "${{ steps.changelog.outputs.CHANGELOG }}"
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}