name: Build Kumo
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from build.gradle.kts
        id: get_version
        run: |
          # Extrae la versión del archivo build.gradle.kts
          VERSION=$(grep 'versionName =' app/build.gradle.kts | cut -d '"' -f 2)
          # Añade un timestamp para hacer el tag único
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "Versión encontrada: $VERSION"
          echo "TAG=v${VERSION}-${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: gradle

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG=$(git log --pretty=format:"- %h %s")
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Decode keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d > app/nube.p12

      - name: Build release APKs
        run: |
          ./gradlew assembleRelease --stacktrace --parallel --max-workers=$(nproc)

      - name: Sign APKs
        run: |
          ANDROID_BUILD_TOOLS="$ANDROID_HOME/build-tools/$(ls $ANDROID_HOME/build-tools | sort -V | tail -n1)"
          
          sign_apk() {
            local arch=$1
            local unsigned_path="app/build/outputs/apk/release/app-${arch}-release-unsigned.apk"
            local signed_name="kumo-${{ steps.get_version.outputs.VERSION }}-${arch}-release-signed.apk"
            
            [ -f "$unsigned_path" ] || { echo "APK not found for ${arch}"; return 1; }
            
            "$ANDROID_BUILD_TOOLS/apksigner" sign \
              --ks app/nube.p12 \
              --ks-key-alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
              --ks-pass pass:"${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
              --key-pass pass:"${{ secrets.RELEASE_KEY_PASSWORD }}" \
              --out app/build/outputs/apk/release/$signed_name \
              "$unsigned_path"
          }
          
          sign_apk "armeabi-v7a"
          sign_apk "arm64-v8a"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.TAG }}
          name: "Versión ${{ steps.get_version.outputs.VERSION }}"
          files: |
            app/build/outputs/apk/release/kumo-${{ steps.get_version.outputs.VERSION }}-armeabi-v7a-release-signed.apk
            app/build/outputs/apk/release/kumo-${{ steps.get_version.outputs.VERSION }}-arm64-v8a-release-signed.apk
          body: "${{ steps.changelog.outputs.CHANGELOG }}"
          draft: false
          prerelease: false
